# General info:
title: GitHub Pages skeleton
description: > #ignore newlines
  A skeleton to quickly create GitHub pages with blog
author: insomnux
url: https://


# Site options:
permalink: /articles/:title
baseurl: /ghpages-skeleton/
# favicon: assets/favicon.ico
# logo: assets/logo.png

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  hard_wrap: false

# Social links
twitter_un: user
github_un: insomnux 
